### ISSUE TITLE
README Fixes

### ISSUE THREAD

**Issue by rcass** [DanielKell/Inhabitent_WP#2]
Great work so far, there are some README changes I thought I would point out so you don't forget about them!

- [x] Create a README.md for your project (so this will be in the root of your project, aka the root of wp-content)

- [x] Modify the Theme readme. There is a readme file in the theme, it currently just has the placeholder text. So be sure to update this before handing it in.

- [x] Modify the Plugin readme. There is a readme file in the plugin, just has placeholder text, so be sure to update it.

Let me know if you have any questions! 👍  good job so far!

**Comment by DanielKell** [comment]
Updated these!

**Comment by rcass** [comment]
Just need to update the plugin readmes! They still have the default text! 

Your main project README looks good 👍

**Comment by DanielKell** [comment]
Oops sorry I didn't see that they hadn't saved previously! Changed now.

**Comment by rcass** [comment]
Perfect! I'll close this now then!
