### ISSUE TITLE
No need for single-post.php

### ISSUE THREAD

**Issue by rcass** [DanielKell/Inhabitent_WP#3]
The starter theme out of the box came with basic blog functionality, meaning for displaying a single post is was just using single.php.

Since there there is not content/php changes needed to be done the default it fine. (You will just need to apply css).

Basically you should not need a single-post.php, since single.php exists.

- [x] Delete single-post.php

* Here is the [template hierarchy](https://wphierarchy.com/) for reference.
* [Article](https://premium.wpmudev.org/blog/guide-wordpress-template-hierarchy/) for reference. There are more resources in the template hierarchy lesson page as well.

**Comment by DanielKell** [comment]
Fixed

**Comment by rcass** [comment]
Perfect! 💯
